using Le.WeChat.Model.Model;
using Le.WeChat.Service.IService;

namespace Le.WeChat.Service.Service;

public class EmojiService : IEmojiService
{
    public IEnumerable<EmojiModel> GetAllEmojiModel()
    {
        return new List<EmojiModel>
        {
            new EmojiModel { EmojiName = "Grinning Face", EmojiCode = "😀" },
            new EmojiModel { EmojiName = "Beaming Face with Smiling Eyes", EmojiCode = "😁" },
            new EmojiModel { EmojiName = "Face with Tears of Joy", EmojiCode = "😂" },
            new EmojiModel { EmojiName = "Smiling Face with Heart-Eyes", EmojiCode = "😍" },
            new EmojiModel { EmojiName = "Smiling Face with Sunglasses", EmojiCode = "😎" },
            new EmojiModel { EmojiName = "Thinking Face", EmojiCode = "🤔" },
            new EmojiModel { EmojiName = "Crying Face", EmojiCode = "😢" },
            new EmojiModel { EmojiName = "Red Heart", EmojiCode = "❤️" },
            new EmojiModel { EmojiName = "Thumbs Up", EmojiCode = "👍" },
            new EmojiModel { EmojiName = "Clapping Hands", EmojiCode = "👏" },
            new EmojiModel { EmojiName = "Folded Hands", EmojiCode = "🙏" },
            new EmojiModel { EmojiName = "Rocket", EmojiCode = "🚀" },
            new EmojiModel { EmojiName = "Fire", EmojiCode = "🔥" },
            new EmojiModel { EmojiName = "Party Popper", EmojiCode = "🎉" },
            new EmojiModel { EmojiName = "Face Blowing a Kiss", EmojiCode = "😘" },
            new EmojiModel { EmojiName = "Winking Face", EmojiCode = "😉" },
            new EmojiModel { EmojiName = "Zany Face", EmojiCode = "🤪" },
            new EmojiModel { EmojiName = "Money-Mouth Face", EmojiCode = "🤑" },
            new EmojiModel { EmojiName = "Face Screaming in Fear", EmojiCode = "😱" },
            new EmojiModel { EmojiName = "Sleeping Face", EmojiCode = "😴" },
            new EmojiModel { EmojiName = "Relieved Face", EmojiCode = "😌" },
            new EmojiModel { EmojiName = "Face with Rolling Eyes", EmojiCode = "🙄" },
            new EmojiModel { EmojiName = "Exploding Head", EmojiCode = "🤯" },
            new EmojiModel { EmojiName = "Victory Hand", EmojiCode = "✌️" },
            new EmojiModel { EmojiName = "OK Hand", EmojiCode = "👌" },
            new EmojiModel { EmojiName = "Thumbs Down", EmojiCode = "👎" },
            new EmojiModel { EmojiName = "Raised Fist", EmojiCode = "✊" },
            new EmojiModel { EmojiName = "Flexed Biceps", EmojiCode = "💪" },
            new EmojiModel { EmojiName = "Face with Medical Mask", EmojiCode = "😷" },
            new EmojiModel { EmojiName = "Face with Thermometer", EmojiCode = "🤒" },
            new EmojiModel { EmojiName = "Face with Head-Bandage", EmojiCode = "🤕" },
            new EmojiModel { EmojiName = "Nerd Face", EmojiCode = "🤓" },
            new EmojiModel { EmojiName = "Cowboy Hat Face", EmojiCode = "🤠" },
            new EmojiModel { EmojiName = "Face with Monocle", EmojiCode = "🧐" },
            new EmojiModel { EmojiName = "Smiling Face with Halo", EmojiCode = "😇" },
            new EmojiModel { EmojiName = "Shushing Face", EmojiCode = "🤫" },
            new EmojiModel { EmojiName = "Face with Hand Over Mouth", EmojiCode = "🤭" },
            new EmojiModel { EmojiName = "Face Vomiting", EmojiCode = "🤮" },
            new EmojiModel { EmojiName = "Skull", EmojiCode = "💀" },
            new EmojiModel { EmojiName = "Ghost", EmojiCode = "👻" },
            new EmojiModel { EmojiName = "Alien", EmojiCode = "👽" },
            new EmojiModel { EmojiName = "Robot", EmojiCode = "🤖" },
            new EmojiModel { EmojiName = "Pile of Poo", EmojiCode = "💩" },
            new EmojiModel { EmojiName = "Smiling Face with Horns", EmojiCode = "😈" },
            new EmojiModel { EmojiName = "Angry Face with Horns", EmojiCode = "👿" },
            new EmojiModel { EmojiName = "Unicorn Face", EmojiCode = "🦄" },
            new EmojiModel { EmojiName = "Rainbow", EmojiCode = "🌈" },
            new EmojiModel { EmojiName = "Sun with Face", EmojiCode = "🌞" },
            new EmojiModel { EmojiName = "Moon Face", EmojiCode = "🌝" },
            new EmojiModel { EmojiName = "Pouting Face", EmojiCode = "😡" },
            new EmojiModel { EmojiName = "Angry Face", EmojiCode = "😠" },
            new EmojiModel { EmojiName = "Crying Face", EmojiCode = "😭" },
            new EmojiModel { EmojiName = "Cold Face", EmojiCode = "🥶" },
            new EmojiModel { EmojiName = "Hot Face", EmojiCode = "🥵" },
            new EmojiModel { EmojiName = "Face with Steam From Nose", EmojiCode = "😤" },
            new EmojiModel { EmojiName = "Face with Symbols on Mouth", EmojiCode = "🤬" },
            new EmojiModel { EmojiName = "Confounded Face", EmojiCode = "😖" },
            new EmojiModel { EmojiName = "Persevering Face", EmojiCode = "😣" },
            new EmojiModel { EmojiName = "Face with Cold Sweat", EmojiCode = "😓" },
            new EmojiModel { EmojiName = "Weary Face", EmojiCode = "😩" },
            new EmojiModel { EmojiName = "Tired Face", EmojiCode = "😫" },
            new EmojiModel { EmojiName = "Pleading Face", EmojiCode = "🥺" },
            new EmojiModel { EmojiName = "Yawning Face", EmojiCode = "🥱" },
            new EmojiModel { EmojiName = "Loudly Crying Face", EmojiCode = "😭" },
            new EmojiModel { EmojiName = "Tears of Joy", EmojiCode = "😂" },
            new EmojiModel { EmojiName = "Face with Open Mouth", EmojiCode = "😮" },
            new EmojiModel { EmojiName = "Hushed Face", EmojiCode = "😯" },
            new EmojiModel { EmojiName = "Astonished Face", EmojiCode = "😲" },
            new EmojiModel { EmojiName = "Flushed Face", EmojiCode = "😳" },
            new EmojiModel { EmojiName = "Dizzy Face", EmojiCode = "😵" },
            new EmojiModel { EmojiName = "Face with Crossed-Out Eyes", EmojiCode = "😵‍💫" },
            new EmojiModel { EmojiName = "Sleeping Face", EmojiCode = "😴" },
            new EmojiModel { EmojiName = "Drooling Face", EmojiCode = "🤤" },
            new EmojiModel { EmojiName = "Face Without Mouth", EmojiCode = "😶" },
            new EmojiModel { EmojiName = "Zipper-Mouth Face", EmojiCode = "🤐" },
            new EmojiModel { EmojiName = "Face with Raised Eyebrow", EmojiCode = "🤨" },
            new EmojiModel { EmojiName = "Neutral Face", EmojiCode = "😐" },
            new EmojiModel { EmojiName = "Expressionless Face", EmojiCode = "😑" },
            new EmojiModel { EmojiName = "Face with Rolling Eyes", EmojiCode = "🙄" },
            new EmojiModel { EmojiName = "Smirking Face", EmojiCode = "😏" },
            new EmojiModel { EmojiName = "Face with Tongue", EmojiCode = "😛" },
            new EmojiModel { EmojiName = "Winking Face with Tongue", EmojiCode = "😜" },
            new EmojiModel { EmojiName = "Squinting Face with Tongue", EmojiCode = "😝" },
            new EmojiModel { EmojiName = "Money-Mouth Face", EmojiCode = "🤑" },
            new EmojiModel { EmojiName = "Shushing Face", EmojiCode = "🤫" },
            new EmojiModel { EmojiName = "Face with Medical Mask", EmojiCode = "😷" },
            new EmojiModel { EmojiName = "Face with Thermometer", EmojiCode = "🤒" },
            new EmojiModel { EmojiName = "Face with Head-Bandage", EmojiCode = "🤕" },
            new EmojiModel { EmojiName = "Nauseated Face", EmojiCode = "🤢" },
            new EmojiModel { EmojiName = "Face Vomiting", EmojiCode = "🤮" },
            new EmojiModel { EmojiName = "Sneezing Face", EmojiCode = "🤧" },
            new EmojiModel { EmojiName = "Cowboy Hat Face", EmojiCode = "🤠" },
            new EmojiModel { EmojiName = "Clown Face", EmojiCode = "🤡" },
            new EmojiModel { EmojiName = "Robot Face", EmojiCode = "🤖" },
            new EmojiModel { EmojiName = "Grinning Cat", EmojiCode = "😺" },
            new EmojiModel { EmojiName = "Smiling Cat with Heart-Eyes", EmojiCode = "😻" },
            new EmojiModel { EmojiName = "Cat with Tears of Joy", EmojiCode = "😹" },
            new EmojiModel { EmojiName = "Pouting Cat", EmojiCode = "😾" },
            new EmojiModel { EmojiName = "Kiss Mark", EmojiCode = "💋" },
            new EmojiModel { EmojiName = "Love Letter", EmojiCode = "💌" },
            new EmojiModel { EmojiName = "Gift Heart", EmojiCode = "💝" },
            new EmojiModel { EmojiName = "Heart with Arrow", EmojiCode = "💘" }
        };
    }
}